In [13]:
import pandas as pd
import numpy as np

In [20]:
df = pd.DataFrame({"A":[1, 2, 3, np.nan],
                  "B":[5, np.nan, 6, 7],
                  "C":[9, 3, np.nan, 1]})
df

A    B    C
0  1.0  5.0  9.0
1  2.0  NaN  3.0
2  3.0  6.0  NaN
3  NaN  7.0  1.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       4 non-null      int64  
 1   B       3 non-null      float64
 2   C       3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes


In [25]:
df.notna()

A      B      C
0   True   True   True
1   True  False   True
2   True   True  False
3  False   True   True

In [29]:
df.describe()

A    B         C
count  3.0  3.0  3.000000
mean   2.0  6.0  4.333333
std    1.0  1.0  4.163332
min    1.0  5.0  1.000000
25%    1.5  5.5  2.000000
50%    2.0  6.0  3.000000
75%    2.5  6.5  6.000000
max    3.0  7.0  9.000000

In [33]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

data = [1,2,2,5,3,5,1]

encoder.fit(data)

transformed = encoder.transform(data)

inverse = encoder.inverse_transform(transformed)

print(encoder.classes_)
print(transformed)
print(inverse)

[1 2 3 5]
[0 1 1 3 2 3 0]
[1 2 2 5 3 5 1]


In [35]:
data = ['Tokyo', 'Mumbai', 'Reykajvik', 'Shimla']

encoder.fit(data)
transformed = encoder.transform(data)
inverse = encoder.inverse_transform(transformed)

print(encoder.classes_)
print(transformed)
print(inverse)

['Mumbai' 'Reykajvik' 'Shimla' 'Tokyo']
[3 0 1 2]
['Tokyo' 'Mumbai' 'Reykajvik' 'Shimla']


In [36]:
data = ['Tokyo', 'Mumbai', 'Reykajvik', 'Shimla']

encoder.fit(data)
transformed = encoder.transform(data)

new_data = [1, 2, 3, 0, 1, 1, 3, 0]
inverse = encoder.inverse_transform(new_data)

print(encoder.classes_)
print(transformed)
print(inverse)

['Mumbai' 'Reykajvik' 'Shimla' 'Tokyo']
[3 0 1 2]
['Reykajvik' 'Shimla' 'Tokyo' 'Mumbai' 'Reykajvik' 'Reykajvik' 'Tokyo'
 'Mumbai']
